### ISSUE TITLE
Static screenshot file name overwrite.

### ISSUE THREAD

**Issue by KiNGKiMO** [artem78/AutoScreenshot#16]
Hello, 

Thank you for such a great tool, I'm having an issue where the app does not overwrite the set static screenshot name, instead it creates a new file name each time "screenshot (2).jpg, screenshot (3).jpg, ETC".

**Comment by artem78** [comment]
Yes, it is normal behavior and not a bug. It's possible to add "overwrite" option.

**Comment by KiNGKiMO** [comment]
This could be very useful, thank you.

**Comment by artem78** [comment]
> It's possible to add "overwrite" option.

But I think you\`re right and it will be better to **enable file overwrite** as default without additional option. If user needs to disable overwriting he may use sequential number variable `%NUM` in file name. Fox example for filename template `screenshot %NUM`, files will be named as screenshot 1.jpg, screenshot 2.jpg, screenshot 3.jpg, etc...

What do you think about it?

**Comment by KiNGKiMO** [comment]
Exactly, I think what would be the best thing to do yes.

**Comment by artem78** [comment]
Added in [version 1.8.1](https://github.com/artem78/AutoScreenshot/releases/tag/v1.8.1)
