### ISSUE TITLE
scaled windows do not capture properly

### ISSUE THREAD

**Issue by florisjan78** [artem78/AutoScreenshot#17]
**Describe the bug**
I have 1 4k screen and 2 1920x1200s. The resolution is increased virtually by windows due to scaling it seems and only part of the actual screen appears in the screenshot
**To Reproduce**
use screens with different resolutions with scaling on.

**Version**
Which version of program do you use?
latest - 1.8.2

**Comment by artem78** [comment]
@florisjan78 Could you please show screenshot of your screen settings?

**Comment by artem78** [comment]
Fixed in [v1.10.3](https://github.com/artem78/AutoScreenshot/releases/tag/v1.10.3)
