### ISSUE TITLE
hotkeys to start/stop taking screenshots

### ISSUE THREAD

**Issue by tom-vb** [artem78/AutoScreenshot#19]
Hello, I just discoverd this sofware and is just what I was looking for. Simple and effective. In my case this software is what I was looking for, but I would like to be able to stop and restart the screenshots with a hotkey of keyboard without having to open the program window.

Greetings and congratulations for the work done.

**Comment by artem78** [comment]
Added in v1.10

**Comment by tom-vb** [comment]
that's great, thanks!

**Comment by artem78** [comment]
Defaults (customizable in settings):
 - Ctrl+F5 for start
 - Ctrl+F6 for stop
 - Ctrl+F7 for single screenshot
