### ISSUE TITLE
Error Message on Windows startup

### ISSUE THREAD

**Issue by HolyWill90** [artem78/AutoScreenshot#21]
**Describe the bug**
Error Message
Unable to create file "C:\Program Files (x86)\AutoScreenShot\\config.ini": Access denied.

Then keeps running in the background in task manager but no UI.

**To Reproduce**
1. Windows Start up '...'
2. See error

**Expected behavior**

Not have the error message

**Screenshots**
![AutoScreehshot](https://user-images.githubusercontent.com/28798555/177968969-aceaa2e3-41ef-4037-b052-6343ada0f64a.png)

**Version**
Which version of program do you use?
v1.10

**Comment by artem78** [comment]
Thanks for report.

Do you have this problem only when program starts with Windows? Try to run it manually. Also check write access to program directory.

**Comment by artem78** [comment]
Fixed in v1.10.1. Please check.

Now settings do not stored in `Program Files`. `AppData` directory used instead.
