### ISSUE TITLE
Automatic capture not working on Windows 11

### ISSUE THREAD

**Issue by jbellis** [artem78/AutoScreenshot#25]
Clicking the button to manually trigger a screenshot works, but automatic capture does not.

Is there a log that can help troubleshoot?

**Comment by artem78** [comment]
Could you paste your config file?

**Comment by artem78** [comment]
I add logging. Try to run this build and send me `debug_log.txt` file.
[AutoScreenshot debug build 390ea486.zip](https://github.com/artem78/AutoScreenshot/files/9870804/AutoScreenshot.debug.build.390ea486.zip)

**Comment by artem78** [comment]
Hi, @jbellis !

Let me know if you still have this problem in [latest version 1.12](https://github.com/artem78/AutoScreenshot/releases/tag/v1.12) or I can mark issue as closed?

**Comment by jbellis** [comment]
Something must wonky with github email updates, this is the first message that I saw.  Sorry for the lack of replies earlier!

Unfortunately I gave away the Windows 11 machine I was using and can no longer test.  Closing the issue.
