### ISSUE TITLE
Option for 'delete all screenshot files older than XXX'

### ISSUE THREAD

**Issue by Xyvir** [artem78/AutoScreenshot#31]
**Is your feature request related to a problem? Please describe.**
Too many screenshots on autocapture can fill up PC space quickly.

**Describe the solution you'd like**
Add a option for 'automatically delete screenshots older than XXX Hours/Days/Weeks

**Describe alternatives you've considered**
Manually deleting old screenshots as needed.

**Additional context**
This would be a useful feature for recording for long periods, when you just need to go back 24 hours or so to troubleshoot a paritcular issue.

**Comment by artem78** [comment]
Added in [1.13 release](https://github.com/artem78/AutoScreenshot/releases/tag/v1.13).
