### ISSUE TITLE
change icon to another color when taking screenshots

### ISSUE THREAD

**Issue by tom-vb** [artem78/AutoScreenshot#34]
Hello, I would like to make a suggestion.
It would be nice to be able to configure the icon to change to another color when the program is taking screenshots. And if this functionality could also be activated and deactivated with a shortcut much better.

thank you,
all the best.

**Comment by artem78** [comment]
What OS do you use?

**Comment by tom-vb** [comment]
Hello, thanks for you reply,
I'm on Windows 10 Enterprise LTSC 10.0.17763 with autoscreenshot 1.10.4 . In my case the system tray icon is allways the same, not changes when screenshooting

**Comment by artem78** [comment]
I will check.

**Comment by artem78** [comment]
I have Windows 10 Home 21H2 installed on virtual machine, but can't reproduce problem.

![1](https://github.com/artem78/AutoScreenshot/assets/8585304/8e4e137b-1574-4ca1-b0f8-b2b71daa01c9)

**Comment by tom-vb** [comment]
Hello, thanks for you reply,
well, to tell you the truth, I have small icons on the taskbar and I had never noticed this icon blink! I was referring to the icon blinking continuously or better having another color, not only at the time the screenshot is taken, but all the time it is taking screenshots. To know with a glance at the icon that you have the program capturing
![tZZK4pvEOt](https://github.com/artem78/AutoScreenshot/assets/83949165/116f8cca-a878-4c0f-907b-a5556e5f810b)

**Comment by artem78** [comment]
@tom-vb When auto capturing disabled tray icon is black and white and colored when enabled. Perhaps it poorly visible and need to be highlighted more.

**Comment by tom-vb** [comment]
Hi, thanks for your replay. Now that you mention it, I have noticed it well and that's how it is, but I had to make a brutal effort to distinguish it. You have to have an alcon view to realize it!

thanks,
all the best!

**Comment by artem78** [comment]
Hi, @tom-vb 

I increased contrast between active and inactive icon state by adding transparency. I think now it is more visibly:

![autoscreenshot_icon](https://github.com/artem78/AutoScreenshot/assets/8585304/e15fc70d-92df-4b12-91ed-c4ca2fb7ea52)

Please check latest [v1.14](https://github.com/artem78/AutoScreenshot/releases/tag/v1.14).

**Comment by tom-vb** [comment]
Hi, looks fine. I will update the release. Thaks!!

**Comment by tom-vb** [comment]
I Just installed last release. Looks great. Thanks!

**Comment by artem78** [comment]
Ok. I will mark issue as closed.
