### ISSUE TITLE
Access violation on first run of second instance

### ISSUE THREAD

**Issue by billybednar** [artem78/AutoScreenshot#36]
**Describe the bug**
While testing a fix to #35, I noticed that a fresh portable version (without a config.ini) will crash on its first run if another instance of the application (portable or installed) is already running. It also occurs if the config.ini file does not contain a "LastCheckForUpdates" line (but only if another instance is running).

**To Reproduce**
1. Extract two copies of the portable version into different locations.
2. Run the exe in the first location. The application window will open.
3. Run the exe in the second location. The application window will briefly open, then close with an error message ([text here,](https://github.com/artem78/AutoScreenshot/files/11717534/error_message.txt) screenshot below). A config.ini will also be generated.
4. Run the exe in the second location again. The application window will briefly open and close without error.
5. Delete the config.ini file from the second location.
6. Run the exe in the second location. The error returns.  A new config.ini will be generated.
7. Edit the config.ini file in the second location to remove the "LastCheckForUpdates=..." line and add a "Logging=1" line.
8. Run the exe in the second location. The error occurs again.

**Expected behavior**
The second instance always exits cleanly without crashing, ideally after restoring and activating the already running instance.

**Screenshots**
![image](https://github.com/artem78/AutoScreenshot/assets/1000201/85e8f9f3-ed60-4a3a-89b3-5436c07da9a4)

**Version**
1.11 portable + 1.11 portable, 1.10.4 installed + 1.11-3-g7872c3e-dirty

**OS**
Windows 10 Pro 22H2 (build 19045.2965), 64 bit

**Log file**
[log.txt](https://github.com/artem78/AutoScreenshot/files/11717913/log.txt) (from the second instance; nothing extra is added to the first)

**Comment by artem78** [comment]
Fixed in [v1.12](https://github.com/artem78/AutoScreenshot/releases/tag/v1.12).
