### ISSUE TITLE
Play subtle sound effect for hotkey presses

### ISSUE THREAD

**Issue by Spaceman333** [artem78/AutoScreenshot#39]
I set up hotkeys to take pictures automatically at an interval, but I forgot to turn it off and didn't realize until much later because there was no feedback - the app was just silently doing its thing and creating screenshots, minimized in the tray.

Having a subtle unique sound effect per hotkey + whenever automatic mode does a shot would solve this.

This free tool could be used to create an instant easy sound effect that suits the automatic on/off or single shot:
https://iznaut.itch.io/bfxr

**Comment by artem78** [comment]
>  This free tool could be used to create an instant easy sound effect that suits the automatic on/off or single shot:
> https://iznaut.itch.io/bfxr

I don't know how to use it. If you can provide sound files I can add them to my program.

**Comment by Spaceman333** [comment]
> This free tool could be used to create an instant easy sound effect that suits the automatic on/off or single shot: https://iznaut.itch.io/bfxr
> I don't know how to use it. If you can provide sound files I can add them to my program.

No problem, here you go:
[Sound Effects for Auto Screenshot.zip](https://github.com/artem78/AutoScreenshot/files/12769369/Sound.Effects.for.Auto.Screenshot.zip)

I've included 4 sounds per hotkey, so 12 in total. Choose whichever you like.

The program is very easy despite the many buttons btw, all you need to do is press "Randomize" on the left side and then press Export Wav on the right side. Thats what I used to make these.

**Comment by artem78** [comment]
Thanks. I will try to add them when I will have spare time.

**Comment by artem78** [comment]
Hi, @Spaceman333 

Thanks again for sound files, but I found them not quite suitable and replaced them with others:
https://mega.nz/folder/uZlgVbIT#morCSmQqqXQcyMQx7IM_Bg

Shutter sound found on the web. Start and stop made by me in midi editor.

**Comment by Spaceman333** [comment]
> Hi, @Spaceman333
> 
> Thanks again for sound files, but I found them not quite suitable and replaced them with others: https://mega.nz/folder/uZlgVbIT#morCSmQqqXQcyMQx7IM_Bg
> 
> Shutter sound found on the web. Start and stop made by me in midi editor.

Way better than my minimal abstract ones! I like these new realistic ones a lot. 👍👍

**Comment by artem78** [comment]
I added sounds to the program (by default they disabled). Please check [v1.14](https://github.com/artem78/AutoScreenshot/releases/tag/v1.14).

**Comment by Spaceman333** [comment]
> I added sounds to the program (by default they disabled). Please check [v1.14](https://github.com/artem78/AutoScreenshot/releases/tag/v1.14).

Works beautifully, I feel happy!
