### ISSUE TITLE
Feature Request: Add support for multiple screens

### ISSUE THREAD

**Issue by vgf89** [artem78/AutoScreenshot#4]
I'd like to take a screenshot of all of my screens (I'm running 3 side-by-side) like Window's native screenshot function.

**Comment by artem78** [comment]
Hmm... Not sure, is it possible. Also I have only one display, so will not be able to check this.

> screenshot of all of my screens

You mean in one file side by side?

**Comment by vgf89** [comment]
Yes, preferably. Windows even stitches them together in the same layout
that's set in the display settings, though I suppose that's less important.


On Dec 4, 2020 at 12:49 AM, Artem <notifications@github.com> wrote:

Hmm... Not sure, is it possible. Also I have only one display, so will not
be able to check this.

screenshot of all of my screens

You mean in one file side by side?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/artem78/AutoScreenshot/issues/4#issuecomment-738092474>,
or unsubscribe

**Comment by artem78** [comment]
Okay. I will try to implement this and let you know.

**Comment by artem78** [comment]
Could you please show your monitors multiple settings and what area captured by Auto Screnshot? Is it the same screen, where program located?

**Comment by vgf89** [comment]
Here's what Auto Screenshot captures. It doesn't matter which screen the Auto Screenshot window it on, it always captures my main display (in this case, Screen 2 is set as my Primary Display in the Windows display settings).
![2020-12-07 14 29 39](https://user-images.githubusercontent.com/5163157/101313583-c3bc9580-3899-11eb-8791-5019c36f6ae9.png)

Here's what the Print Screen button captures (I can paste this into Paint to save it like I did here, or if you hold the Windows Key and press the Print Screen key it'll automatically save into your pictures folder)
![Window Print Screen](https://user-images.githubusercontent.com/5163157/101313618-de8f0a00-3899-11eb-8b23-8ab0996cea46.png)

**Comment by artem78** [comment]
Thanks a lot for detailed information and screenshots! It really helps me.

I added some fixes to AutoScreenshot and created test build - 
[autoscreenshot_multiple_monitor_test_build.zip](https://github.com/artem78/AutoScreenshot/files/5654666/autoscreenshot_multiple_monitor_test_build.zip). Could you please try this? Unzip it to any directory and run. Let me know how it works now. Thanks.

**Comment by vgf89** [comment]
Perfect! Here's a couple screenshots from that test build.
My normal layout:
![2020-12-08 11 45 43](https://user-images.githubusercontent.com/5163157/101432170-b8c23d80-394b-11eb-853f-a6b50362cf6e.png)
Funky layout:
![2020-12-08 11 51 04](https://user-images.githubusercontent.com/5163157/101432180-bc55c480-394b-11eb-83ea-91d7a07f660c.png)

Looks like you got it! Awesome!

**Comment by artem78** [comment]
Nice to hear, that it works fine now. Thank you for testing. I will include these changes in next release.
