### ISSUE TITLE
Additional save locations

### ISSUE THREAD

**Issue by JasonUnger** [artem78/AutoScreenshot#43]
**Is your feature request related to a problem? Please describe.**
Add an option to allow for multiple locations to save to

**Describe the solution you'd like**
Instead of a single input for a directory, set up a list with multiple targets on where to save screenshots

**Describe alternatives you've considered**
Running multiple copies of AutoScreenshot, modifying the source (tho I'm not familiar with the language)

**Additional context**
We are using this to take screenshots of a computer, in case a program database becomes unavailable, however would like to save the screenshots to this computer as well as a second backup computer

**Comment by artem78** [comment]
You may run any command after screenshot was taken. Something like: copy 
%FILENAME% C:\Backup\

**Comment by JasonUnger** [comment]
I attempted to use this command almost verbatim in the "Run command" box (I used `copy %FILENAME% C:\Temp\`), however with both the timed capture, as well as clicking the "Take Screenshot" button, no file is created in the second location.

**Comment by JasonUnger** [comment]
![image](https://github.com/artem78/AutoScreenshot/assets/12038059/4d0e9970-c6cd-42df-8f27-67544edd9d73)

**Comment by artem78** [comment]
Try to put in quotation marks source and destination paths: `copy "%FILENAME%" "C:\Temp\"`.

**Comment by artem78** [comment]
I found some mistakes in the source code. Will be fixed in next release. 
Thanks for report.

**Comment by JasonUnger** [comment]
I didn't see your reply, however I think I found what you found: %FILENAME% is off by one second.
![image](https://github.com/artem78/AutoScreenshot/assets/12038059/117abc49-3882-4f8d-a1c4-25e839fb187f)

**Comment by JasonUnger** [comment]
When will the next release happen?

**Comment by artem78** [comment]
> I found what you found: %FILENAME% is off by one second

Yes, but it's not only one problem I found.

> When will the next release happen?

After several days. When I'll go home after vacation.

**Comment by artem78** [comment]
Now fixed in [v1.15](https://github.com/artem78/AutoScreenshot/releases/tag/v1.15)
