### ISSUE TITLE
Close to tray, instead of close completely

### ISSUE THREAD

**Issue by JasonUnger** [artem78/AutoScreenshot#44]
**Is your feature request related to a problem? Please describe.**
Users might accidentally click X instead of _ when opening up the interface

**Describe the solution you'd like**
An option to close to tray instead of closing down completely when clicking the X in the top right of the main configuration

**Describe alternatives you've considered**
N/A

**Additional context**
We need this to be running 100% of the time on our computer, without the user accidentally closing it

**Comment by artem78** [comment]
I think it will be better to simply show confirmation message before 
closing the window.

**Comment by JasonUnger** [comment]
Most tray applications have the option to close to tray, it's an intuitive UIX function. Additionally, when something is started with windows and minimized to tray by default, it's expected to continue running even if the main window is closed, and minimizing to tray (as opposed to using the X close button) isn't intuitive in today's UIX standards or flow.

My use case has someone who moves fast thru things, and doesn't always read dialog boxes, and they want to use this app as a means of capturing data on the screen in case the service they are using becomes non-responsive. Accidentally closing the app could cause problems.

**Comment by artem78** [comment]
> An option to close to tray instead
of closing down completely when
clicking the X in the top right of the
main configuration

In this case both _ and x buttons will do the same thing. And closing the 
application will be possible only from tray icon menu. I think it's a 
little strange.

**Comment by artem78** [comment]
Released [v1.15](https://github.com/artem78/AutoScreenshot/releases/tag/v1.15) with changes related to this issue:

- Confirmation before exit
- Option for close to tray when close window (disabled by default)
