### ISSUE TITLE
please add support the the name of the screenshot be like a incremental

### ISSUE THREAD

**Issue by zodman** [artem78/AutoScreenshot#9]
```
screenshot_1.png
screenshot_2.png 
.....
```

in that way you can run `ffmpeg -i screenshot_%d.png ... -o timelapse.mp4`  very easy!

**Comment by artem78** [comment]
Good idea.

**Comment by artem78** [comment]
Implemented in [1.7 release](https://github.com/artem78/AutoScreenshot/releases/tag/v1.7).

Now you can use this as `screenshot_%NUM`. If you don\`t need leading zeroes will be added, set `Incremental number / Digits` count to 1.
